/// Flutter icons FacebookLike
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FacebookLike
///      fonts:
///       - asset: fonts/FacebookLike.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FacebookLike {
  FacebookLike._();

  static const _kFontFam = 'FacebookLike';

  static const IconData heart_circled = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData ondemand_video = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
  static const IconData thumb_up = IconData(
    0xe802,
    fontFamily: _kFontFam,
  );
  static const IconData users = IconData(
    0xe82b,
    fontFamily: _kFontFam,
  );
  static const IconData alarm = IconData(
    0xe858,
    fontFamily: _kFontFam,
  );
  static const IconData facebook_messenger = IconData(
    0xf39f,
    fontFamily: _kFontFam,
  );
}
